name: Generate and Upload Image

on:
  push:
    branches:
      - main

jobs:
  generate_and_upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Generate image
        run: node generate.js

      - name: Check if file exists
        run: ls output.png
        continue-on-error: true

      - name: Upload image
        uses: actions/upload-artifact@v2
        with:
          name: output.png
          path: output.png
